### ISSUE TITLE
Add support for SqlAlchemy 2.0

### ISSUE THREAD

**Issue by guilhermeleobas** [heavyai/sqlalchemy-heavyai#20]
ref: https://docs.sqlalchemy.org/en/20/changelog/migration_20.html#

**Comment by guilhermeleobas** [comment]
Done in #21

**Comment by charlesbluca** [comment]
Seems there isn't a stable release capturing these changes on PyPI:

- https://pypi.org/project/sqlalchemy-heavyai/#history

Is there any capacity to cut a new release of this project with the changes made in #21?
